name: Generate Games Index
on:
  workflow_dispatch:
  push:
    paths:
      - 'configs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate JSON Index
        run: |
          # 1. Generate games.json (List of game folders)
          if [ -d "configs" ]; then
            ls -d configs/*/ | cut -f2 -d'/' > games.list
            jq -R . games.list | jq -s . > games.json
          else
            echo "[]" > games.json
          fi

          # 2. Generate index.json (Map of Game -> List of Config Files)
          echo "{}" > index.json
          if [ -d "configs" ]; then
            for game in configs/*/; do
              game_name=$(basename "$game")
              configs_list=$(find "$game" -maxdepth 1 -name "*.json" -printf "%f\n")
              
              for config in $configs_list; do
                jq --arg game "$game_name" --arg file "$config" '.[$game] += [$file]' index.json > tmp.json && mv tmp.json index.json
              done
            done
          fi

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add games.json index.json
          git commit -m "Auto-update index [skip ci]" || echo "No changes to commit"
          git push
